notebook:
  build: .
  volumes:
    - ./predict_aqi:/home/jovyan/work/predict_aqi
  ports:
    - "8888:8888"
  command: start-notebook.sh
  links:
    - postgis

postgis:
  image: mdillon/postgis
  ports:
    - "5432:5432"
  volumes:
    - ./postgis:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: douglas
    POSTGRES_DB: AQI
